### ISSUE TITLE
Customers didn't pay but order is completed

### ISSUE THREAD

**Issue by Elenium123** [nartj/sellix-woocommerce#2] opened 2021-04-02 08:50 UTC
Hey. I just woke up to 5-6 orders that are completed but the customers never paid, can you please check it out for me?

**Comment by Elenium123** [comment] 2021-04-02 08:57
I just tried to recreate the issue, as soon as the customer is redirected to the sellix to pay it gets set as completed

**Comment by nartj** [comment] 2021-04-02 09:09
Hey,
Maybe it's caused by what we did yesterday, hence the addon to complete the order.
I removed that part, can you check after updating the plugin :
- if a normal payment is dcorrectly completed
- if you can recreate the mentionned issue

**Comment by Elenium123** [comment] 2021-04-02 09:19
Normal payment doesn't get completed
Can't recreate the issue now

**Comment by nartj** [comment] 2021-04-02 09:26
I re-added error logs, please reactivate debug mode and logging, then check :
- if a normal payment is correctly completed
- if you can recreate the mentionned issue
(do these test in this order)
If still not working, drop the log file there.

**Comment by Elenium123** [comment] 2021-04-02 09:31
[php-errors (5).log](https://github.com/nartj/sellix-woocommerce/files/6248823/php-errors.5.log)
Normal payment not completed
can't recreate the issue

**Comment by Elenium123** [comment] 2021-04-02 09:36
Actually it seems to be good now, i just tried again and its correctly completed

**Comment by nartj** [comment] 2021-04-02 09:40
Remove your logfile, clean up payments and retry both cases.
If still not working, leave logs there

**Comment by Elenium123** [comment] 2021-04-02 09:48
[php-errors (6).log](https://github.com/nartj/sellix-woocommerce/files/6248876/php-errors.6.log)
I tried on another order, sent a paid webhook from sellix but not completed, when i tried ordering and actually paying it got set as completed

**Comment by nartj** [comment] 2021-04-02 09:54
Then, what is the problem exactly? 
The logs shows your "dummy" payment (I guess the one manually tested from sellix by sending the webhook) is marked as "VOIDED" :
[id] => 2166538
[invoice_id] => dummy
[status] => VOIDED
[details] => The invoice has been voided: we have not received a payment within the time limit.
[created_at] => 1605114081

Then, when trying to validate this payment, the HHTP response code is 401 Unauthorized, didi you correctly set up your API key when activating webhook from your sellix dashboard?

The logs shows only one try, although you said you made two (1  for both cases).

Please do the test the same way you did the others, the problem here has nothing to do with the issue you mentionned.

**Comment by Elenium123** [comment] 2021-04-02 09:56
I think everything is fine now. Paying normally is correctly getting completed. and couldn't recreate the issue I mentioned at all

**Comment by nartj** [comment] 2021-04-02 09:58
Okay, nice then. Closed the issue, feel free to reopen it if you can recreate the bug.

**Closed as completed** 2021-04-02 09:59 UTC
